import { precacheAndRoute } from 'workbox-precaching';

import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts',
        plugins: [
            new ExpirationPlugin({ maxEntries: 20 }),
        ],
    })
);

// Cache common image assets
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache script and style files
registerRoute(
    ({ request }) => request.destination === 'script' || request.destination === 'style',
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
    })
);

// Handle Push Notifications
self.addEventListener('push', (event) => {
    const data = event.data ? event.data.json() : {};
    const title = data.title || 'New Call';
    const options = {
        body: data.body || 'Someone is calling you...',
        icon: '/icons/icon-192.png',
        badge: '/icons/icon-192.png',
        data: {
            url: data.url || '/'
        },
        actions: [
            { action: 'accept', title: 'Accept' },
            { action: 'decline', title: 'Decline' }
        ],
        vibrate: [200, 100, 200, 100, 200, 100, 200],
        tag: 'call-notification',
        renotify: true
    };

    event.waitUntil(
        self.registration.showNotification(title, options)
    );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    if (event.action === 'accept') {
        event.waitUntil(
            clients.openWindow(event.notification.data.url + '?action=accept')
        );
    } else {
        // Decline action or just clicking the notification
        event.waitUntil(
            clients.openWindow(event.notification.data.url)
        );
    }
});

// Cache API calls or other dynamic content if needed
self.addEventListener('fetch', (event) => {
    // Custom fetch logic can go here
});
