import { precacheAndRoute } from 'workbox-precaching';

import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts',
        plugins: [
            new ExpirationPlugin({ maxEntries: 20 }),
        ],
    })
);

// Cache common image assets
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    })
);

// Cache script and style files
registerRoute(
    ({ request }) => request.destination === 'script' || request.destination === 'style',
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
    })
);

// Handle Push Notifications
self.addEventListener('push', (event) => {
    let data = {};
    try {
        data = event.data ? event.data.json() : {};
    } catch (e) {
        data = { title: 'New Notification', body: event.data ? event.data.text() : 'You have a new alert' };
    }

    const title = data.title || 'FYP Notification';
    const options = {
        body: data.body || 'New activity in Find Your Painter',
        icon: '/icons/icon-192.png',
        badge: '/icons/icon-192.png',
        data: {
            url: data.url || '/',
            type: data.type || 'generic'
        },
        vibrate: [200, 100, 200, 100, 200, 100, 200],
        tag: data.tag || 'fyp-notification',
        renotify: true,
        requireInteraction: data.type === 'call' // Keep calls active
    };

    if (data.type === 'call') {
        options.actions = [
            { action: 'accept', title: 'Accept Call' },
            { action: 'decline', title: 'Decline' }
        ];
    }

    event.waitUntil(
        self.registration.showNotification(title, options)
    );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = new URL(event.notification.data.url, self.location.origin).href;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window open
            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (clients.openWindow) {
                return clients.openWindow(urlToOpen + (event.action === 'accept' ? '?action=accept' : ''));
            }
        })
    );
});

// Cache API calls or other dynamic content if needed
self.addEventListener('fetch', (event) => {
    // Custom fetch logic can go here
});
